services:
  redis:
    image: redis:latest
    container_name: nicobank-redis-dev
    ports:
      - "6379:6379"
    networks:
      - nicobank-dev

  nicobank:
    build: .
    container_name: nicobank-app-dev
    env_file:
      - .env
    environment:
      - ENV=development
    depends_on:
      - redis
    networks:
      - nicobank-dev
    command: python main.py
    volumes:
      - .:/app

  tests:
    build: .
    container_name: nicobank-tests-dev
    env_file:
      - .env
    environment:
      - ENV=development
    depends_on:
      - redis
    networks:
      - nicobank-dev
    command: pytest /app/tests --maxfail=1 --disable-warnings
    volumes:
      - .:/app

networks:
  nicobank-dev:
    driver: bridge